Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Core import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Neighbourhood.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Neighbourhood/urls.py
from Neighbourhood import views
from django.urls import path
from django.conf.urls.static import static
from Core import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.Home, name="Home"),
    path('register', views.Register, name="Register"),
    path('login', views.Login, name="Login"),
    path('logout', views.Logout, name="Logout"),
    path('profile/<str:username>/settings', views.Settings, name="Settings"),
    path('profile/<str:username>/edit', views.EditProfile, name="EditProfile"),
    path('profile/<str:username>', views.MyProfile, name="MyProfile"),
    path('activateuser/<uidb64>/<token>',views.ActivateAccount, name = 'ActivateAccount'),
    path('resetpassword/',auth_views.PasswordResetView.as_view(template_name='ResetPassword.html'), name = 'reset_password'),
    path('resetpassword/sent/',auth_views.PasswordResetDoneView.as_view(template_name='PasswordResetSent.html'), name = 'password_reset_done'),
    path('resetpassword/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='PasswordResetConfirm.html'), name = 'password_reset_confirm'),
    path('resetpassword/success/',auth_views.PasswordResetCompleteView.as_view(template_name='PasswordResetSuccess.html'), name = 'password_reset_complete'),
    path('<str:username>/add/business/', views.AddBusiness, name='AddBusiness'),
    path('<str:username>/add/neighbourhood/', views.AddNeighbourhood, name='AddNeighbourhood'),
    path('<str:username>/neighbourhoods/', views.MyNeighbourhoods, name='MyNeighbourhoods'),
    path('<str:username>/posts/', views.MyPosts, name='MyPosts'),
    path('<str:username>/businesses/', views.MyBusinesses, name='MyBusinesses'),
    path('search', views.Search, name="Search"),
    path('<str:username>/add/post/', views.AddPost, name='AddPost'),
    path('join/neighbourhood/<str:title>', views.JoinNeighbourhood, name="JoinNeighbourhood"),
    path('leave/neighbourhood/<str:title>', views.LeaveNeighbourhood, name="LeaveNeighbourhood"),
    path('neighbourhood/<str:title>/', views.SingleNeighbourhood, name='SingleNeighbourhood'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Neighbourhood/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

COUNTIES = [
    ('', ('Choose')), 
    ('Baringo', ('Baringo')),
    ('Bomet', ('Bomet')),
    ('Bungoma ', ('Bungoma ')),
    ('Busia', ('Busia')),
    ('Elgeyo Marakwet', ('Elgeyo Marakwet')),
    ('Embu', ('Embu')),
    ('Garissa', ('Garissa')),
    ('Homa Bay', ('Homa Bay')),
    ('Isiolo', ('Isiolo')),
    ('Kajiado', ('Kajiado')),
    ('Kakamega', ('Kakamega')),
    ('Kericho', ('Kericho')),
    ('Kiambu', ('Kiambu')),
    ('Kilifi', ('Kilifi')),
    ('Kirinyaga', ('Kirinyaga')),
    ('Kisii', ('Kisii')),
    ('Kisumu', ('Kisumu')),
    ('Kitui', ('Kitui')),
    ('Kwale', ('Kwale')),
    ('Laikipia', ('Laikipia')),
    ('Lamu', ('Lamu')),
    ('Machakos', ('Machakos')),
    ('Makueni', ('Makueni')),
    ('Mandera', ('Mandera')),
    ('Meru', ('Meru')),
    ('Migori', ('Migori')),
    ('Marsabit', ('Marsabit')),
    ('Mombasa', ('Mombasa')),
    ('Muranga', ('Muranga')),
    ('Nairobi', ('Nairobi')),
    ('Nakuru', ('Nakuru')),
    ('Nandi', ('Nandi')),
    ('Narok', ('Narok')),
    ('Nyamira', ('Nyamira')),
    ('Nyandarua', ('Nyandarua')),
    ('Nyeri', ('Nyeri')),
    ('Samburu', ('Samburu')),
    ('Siaya', ('Siaya')),
    ('Taita Taveta', ('Taita Taveta')),
    ('Tana River', ('Tana River')),
    ('Tharaka Nithi', ('Tharaka Nithi')),
    ('Trans Nzoia', ('Trans Nzoia')),
    ('Turkana', ('Turkana')),
    ('Uasin Gishu', ('Uasin Gishu')),
    ('Vihiga', ('Vihiga')),
    ('Wajir', ('Wajir')),
    ('West Pokot', ('West Pokot')),
]

CHOICES = [
    ('1', 'Crimes and Safety'),
    ('2', 'Health Emergency'),
    ('3', 'Recommendations'),
    ('4', 'Fire Breakouts'),
    ('5', 'Lost and Found'),
    ('6', 'Death'),
    ('7', 'Event'),
]

# Create your models here.
class NeighbourHood(models.Model):
    title = models.CharField(max_length=150, verbose_name='Neighbourhood Title', null=True, blank=True)
    description = models.TextField(max_length=254, blank=True, verbose_name='Description')
    location = models.CharField(max_length=150, verbose_name='Neighbourhood Location', null=True, blank=True)
    county = models.CharField(choices=COUNTIES, max_length=150, verbose_name='Neighbourhood County', null=True, blank=True)
    neighbourhood_logo = CloudinaryField('neighbourhood_logo')
    neighbourhood_admin = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Neighbourhood Admin')
    health_department = models.CharField(max_length=15, null=True, blank=True, verbose_name='Health Department')
    police_department = models.CharField(max_length=15, null=True, blank=True, verbose_name='Police Department')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Date Created')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='Date Updated')

    def get_neighbourhoods(self):
        neighbourhoods = NeighbourHood.objects.all()
        return neighbourhoods
    
    def create_neigbourhood(self):
        self.save()

    def delete_neigbourhood(self):
        self.delete()

    def find_neigbourhood(self,neigborhood_id):
        neigbourhood = NeighbourHood.objects.filter(self = neigborhood_id)
        return neigbourhood

    def update_neighborhood(self, id, title, location, county, neighbourhood_logo):
        update = NeighbourHood.objects.filter(id = id).update(title = title , location = location, county = county, neighbourhood_logo = neighbourhood_logo)
        return update

    def __str__(self):
        return str(self.title)
    
    class Meta:
        verbose_name_plural = 'NeighbourHoods'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='User')
    bio = models.TextField(max_length=254, blank=True, verbose_name='Bio')
    national_id = models.CharField(max_length=10, blank=True, verbose_name='National ID')
    profile_picture = CloudinaryField('profile_picture')
    neighbourHood = models.ForeignKey(NeighbourHood, on_delete=models.CASCADE, null=True, blank=True, verbose_name='NeighbourHood')
    email_confirmed = models.BooleanField(default=False, verbose_name='Is Confirmed?')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Date Created')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='Date Updated')
    
    def __str__(self):
        return str(self.user.username)
    
    class Meta:
        verbose_name_plural = 'Profiles'

class Business(models.Model):
    name = models.CharField(max_length=150, verbose_name='Business Name', null=True, blank=True)
    description = models.TextField(blank=True, verbose_name='Description')
    email = models.CharField(max_length=150, verbose_name='Business Email Address', null=True, blank=True)
    neighbourhood = models.ForeignKey(NeighbourHood, on_delete=models.CASCADE, verbose_name='NeighbourHood')
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Business Owner')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Date Created')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='Date Updated')

    def __str__(self):
        return str(self.name)

    def get_businesses(self):
        businesses = Business.objects.all()
        return businesses

    def create_business(self):
        self.save()

    def delete_business(self):
        self.delete()

    def find_business(self,business_id):
        business = Business.objects.filter(self = business_id)
        return business

    def update_business(self, id, name, description, email, neighbourhood):
        update = NeighbourHood.objects.filter(id = id).update(name = name , description = description, email = email, neighbourhood = neighbourhood)
        return update
    
    class Meta:
        verbose_name_plural = 'Businesses'

class Post(models.Model):
    title = models.CharField(max_length=120, null=True, verbose_name='Post Title')
    description = models.TextField(null=True, verbose_name='Post Description')
    category = models.CharField(max_length=120, choices=CHOICES, verbose_name='Post Category')
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Post Author')
    neighbourhood = models.ForeignKey(NeighbourHood, on_delete=models.CASCADE, verbose_name='Rlated NeighbourHood')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Date Created')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='Date Updated')

    def __str__(self):
        return str(self.title)
    
    class Meta:
        verbose_name_plural = 'Posts'

class Membership(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='User')
    neighbourhood_membership = models.ForeignKey(NeighbourHood, related_name='neighbourhood_member', on_delete=models.CASCADE, verbose_name='NeighbourHood')

    def __str__(self):
        return str(self.user.username + '-' + self.neighbourhood_membership.title)
    
    class Meta:
        verbose_name_plural = 'Memberships'       
        

Neighbourhood/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import SetPasswordForm
from .models import NeighbourHood, Profile

COUNTIES = [
    ('Choose County', ('Choose County')), 
    ('Baringo', ('Baringo')),
    ('Bomet', ('Bomet')),
    ('Bungoma ', ('Bungoma ')),
    ('Busia', ('Busia')),
    ('Elgeyo Marakwet', ('Elgeyo Marakwet')),
    ('Embu', ('Embu')),
    ('Garissa', ('Garissa')),
    ('Homa Bay', ('Homa Bay')),
    ('Isiolo', ('Isiolo')),
    ('Kajiado', ('Kajiado')),
    ('Kakamega', ('Kakamega')),
    ('Kericho', ('Kericho')),
    ('Kiambu', ('Kiambu')),
    ('Kilifi', ('Kilifi')),
    ('Kirinyaga', ('Kirinyaga')),
    ('Kisii', ('Kisii')),
    ('Kisumu', ('Kisumu')),
    ('Kitui', ('Kitui')),
    ('Kwale', ('Kwale')),
    ('Laikipia', ('Laikipia')),
    ('Lamu', ('Lamu')),
    ('Machakos', ('Machakos')),
    ('Makueni', ('Makueni')),
    ('Mandera', ('Mandera')),
    ('Meru', ('Meru')),
    ('Migori', ('Migori')),
    ('Marsabit', ('Marsabit')),
    ('Mombasa', ('Mombasa')),
    ('Muranga', ('Muranga')),
    ('Nairobi', ('Nairobi')),
    ('Nakuru', ('Nakuru')),
    ('Nandi', ('Nandi')),
    ('Narok', ('Narok')),
    ('Nyamira', ('Nyamira')),
    ('Nyandarua', ('Nyandarua')),
    ('Nyeri', ('Nyeri')),
    ('Samburu', ('Samburu')),
    ('Siaya', ('Siaya')),
    ('Taita Taveta', ('Taita Taveta')),
    ('Tana River', ('Tana River')),
    ('Tharaka Nithi', ('Tharaka Nithi')),
    ('Trans Nzoia', ('Trans Nzoia')),
    ('Turkana', ('Turkana')),
    ('Uasin Gishu', ('Uasin Gishu')),
    ('Vihiga', ('Vihiga')),
    ('Wajir', ('Wajir')),
    ('West Pokot', ('West Pokot')),
]

CATEGORIES = [
    ('1', 'Crimes and Safety'),
    ('2', 'Health Emergency'),
    ('3', 'Recommendations'),
    ('4', 'Fire Breakouts'),
    ('5', 'Lost and Found'),
    ('6', 'Death'),
    ('7', 'Event'),
]

class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-4'}))
    last_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-4'}))
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-4'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-4', 'readonly':'readonly'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

class UpdateProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'dropify', 'data-height':420, 'data-max-file-size':"1M"}))
    bio = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control mb-4', 'rows': 5, 'placeholder':'Keep it short, preferably in one concise sentence'}))
    national_id = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'class': 'form-control mb-4', 'placeholder':'National ID'}))
    neighbourhood = forms.ChoiceField(label=u'Select Your Neighbourhood', required=True, widget=forms.Select(attrs={'class': 'form-control mb-4'}))

    def __init__(self, *args, **kwargs):
        super(UpdateProfileForm, self).__init__(*args, **kwargs)
        self.fields['neighbourhood'].choices = [(e.id, e.title) for e in NeighbourHood.objects.all()]
    
    class Meta:
        model = Profile
        fields = ['profile_picture', 'bio', 'national_id', 'neighbourhood']

class PasswordChangeForm(SetPasswordForm):
    old_password = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class': 'form-control mb-4','type': 'password','name': 'password1','placeholder': 'Old Password',}))
    new_password1 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class': 'form-control mb-4','type': 'password','name': 'password1','placeholder': 'New Password',}))
    new_password2 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class': 'form-control mb-4','type': 'password','name': 'password1','placeholder': 'Confirm Password',}))

    class Meta:
        model = User
        fields = ('old_password','new_password1','new_password2',)

def clean_old_password(self):
    old_password = self.cleaned_data["old_password"]
    if not self.user.check_password(old_password):
        raise forms.ValidationError(
            self.error_messages['password_incorrect'],
            code='password_incorrect',
        )
    return old_password

class AddBussinessForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Business Name','class': 'form-control mb-4'}))
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={'placeholder': 'Business Description','class': 'form-control mb-4','rows': 5,}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'placeholder': 'Business Email','class': 'form-control mb-4'}))
    neighbourhood = forms.ChoiceField(required=True, widget=forms.Select(attrs={'placeholder': 'Neighbourhood','class': 'form-control mb-4'}))

    def __init__(self, *args, **kwargs):
        super(AddBussinessForm, self).__init__(*args, **kwargs)
        self.fields['neighbourhood'].choices = [(e.id, e.title) for e in NeighbourHood.objects.all()]

class AddNeighbourhoodForm(forms.ModelForm):
    title = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Title','class': 'form-control mb-4'}))
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={'placeholder': 'Description','class': 'form-control mb-4','rows': 3,}))
    location = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Location','class': 'form-control mb-4'}))
    county = forms.ChoiceField(required=True, widget=forms.Select( attrs={'class': 'form-control mb-4'}), choices=COUNTIES)
    neighbourhood_logo = forms.ImageField(required=True, widget=forms.FileInput(attrs={'class': 'dropify', 'data-height':300, 'data-max-file-size':"1M"}))
    health_department = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Health Department','class': 'form-control mb-4'}))
    police_department = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Police Department','class': 'form-control mb-4'}))

    class Meta:
        model = NeighbourHood
        fields = ('title','description','location','county','neighbourhood_logo','health_department','police_department')
class AddPostForm(forms.Form):
    title = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-4', 'placeholder':'Post Title'}))
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control mb-4', 'rows': 5, 'placeholder':'Description'}))
    category = forms.ChoiceField(choices=CATEGORIES, required=True, widget=forms.Select(attrs={'class': 'form-control mb-4', 'placeholder':'Select Category'}))
    neighbourhood = forms.ChoiceField(label=u'Select Your Neighbourhood', required=True, widget=forms.Select(attrs={'class': 'form-control mb-4'}))

    def __init__(self, *args, **kwargs):
        super(AddPostForm, self).__init__(*args, **kwargs)
        self.fields['neighbourhood'].choices = [(e.id, e.title) for e in NeighbourHood.objects.all()]

templates/Account Activation Email.html
{% autoescape off %}

Hey {{user.first_name}},

Thank you for signing up with Neigbourhood. To finish your sign up process, please use the link below to verify your Email Address ({{ user.email }}):

https://{{ domain }}{% url 'ActivateAccount' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

Regards,
Team Neigbourhood
{% endautoescape %}

templates/AddBusiness.html
{% extends "Base.html" %}
{% load static %}

{% block content %}
    <div class="container" style="margin-top: 20px;">
        <div>
            {% if messages %}
                {% for message in messages %} 
                <div class="alert {{message.tags}} m-1" role="alert" style="font-size: medium;">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %} 
            {% endif %}
        </div>

        <!-- Breadcrumb -->
        <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)">Business</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add</li>
            </ol>
        </nav>
        <!-- /Breadcrumb -->

        <form method="POST" enctype="multipart/form-data" style="margin-top: 50px;">
            {% csrf_token %}
            <div class="bio layout-spacing ">
                <div class="widget-content widget-content-area">
                    <div class="row">
                        <div class="col-xl-4 col-lg-4 col-md-4">
                            <div class="upload">
                                <label for="fullName">Name <span class="text-danger">*</span></label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-4">
                            <div class="upload">
                                <label for="fullName">Email Address <span class="text-danger">*</span></label>
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-4">
                            <div class="upload">
                                <label for="fullName">Neighbourhood <span class="text-danger">*</span></label>
                                <select name="neighbourhood" class="form-control mb-4" placeholder="Select Neighbourhood">
                                    <option value="" selected disabled>Select Neighbourhood</option>
                                    {% for id, title in form.fields.neighbourhood.choices %}
                                    <option value="{{ id }}">{{ title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-xl-12 col-lg-12 col-md-8 mt-md-0 mt-4">
                            <div class="form">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="fullName">Description <span class="text-danger">*</span></label>
                                            {{ form.description }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary btn-lg btn-block" style="margin-bottom: 10px;">Create Business</button>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <a href="{% url 'MyProfile' user.username %}" name='MyProfile'>
                                                <button type="button" class="btn btn-dark btn-lg btn-block">Cancel</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

    {% block footer %}
        <footer class="page-footer">
            <!-- Copyright -->
            <div class="footer-copyright text-center py-3 text-dark">
                © Copyright 2022 Neighbourhood
            </div>
            <!-- Copyright -->
        </footer>
    {% endblock %}

{% endblock %}

templates/Base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here"/>
    <link rel="shortcut icon" href={% static "assets/img/favicon.png" %}>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href={% static "assets/css/style.css" %}>
    <title>The Neighbourhood - Know your people</title>
</head>
<body>
    {% include 'Navbar.html' %}
    {% block content %}{% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://jeremyfagis.github.io/dropify/dist/js/dropify.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://jeremyfagis.github.io/dropify/dist/css/dropify.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
    <script>$('.dropify').dropify();</script>
</body>
</html>

templates/PasswordResetConfirm.html
{% extends "Base.html" %}
{% load static %}

{% block content %}
    <div class="container" style="margin-top: 20px;">
        <center>
            {% if messages %}
                {% for message in messages %} 
                <div class="alert {{message.tags}} m-1" role="alert" style="font-size: medium;">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %} 
            {% endif %}
        </center>
    </div>
    <div class="forgot-password-form shadow">
        <form action="" method="POST">
            <center>
                <a href="{% url 'Home' %}" name = 'Home' class="logo">
                    <img class="py-4" src={% static "assets/img/logo-2.png" %} alt="" width="100">
                </a>
            </center>
            {% csrf_token %}
            <h2 class="text-center">Reset Password</h2>
            <p class="text-center">Your new password must be different from previously used passwords</p>
            <div class="form-group">
                 <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password" required="true">
            </div> 
            <div class="form-group">
                <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1" required="true">
            </div> 
            <div class="form-group">
                <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2" required="true">
            </div> 
            <button class="btn btn-primary btn-block" type="submit">Set New Password</button>
        </form>
    </div>

    {% block footer %}
        <footer class="page-footer">
            <!-- Copyright -->
            <div class="footer-copyright text-center py-3 text-dark">
                © Copyright 2022 NeighbourHood
            </div>
            <!-- Copyright -->
        </footer>
    {% endblock %}
{% endblock %}

templates/ResetPassword.html
{% extends "Base.html" %}
{% load static %}

{% block content %}
    <div class="container" style="margin-top: 20px;">
        <center>
            {% if messages %}
                {% for message in messages %} 
                <div class="alert {{message.tags}} m-1" role="alert" style="font-size: medium;">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %} 
            {% endif %}
        </center>
    </div>
    <div class="forgot-password-form shadow">
        <form action="" method="POST">
            {% csrf_token %}
            <center>
                <a href="{% url 'Home' %}" name = 'Home' class="logo">
                    <img class="py-4" src={% static "assets/img/logo-2.png" %} alt="" width="100">
                </a>
            </center>
            <h2 class="text-center">Reset Password</h2>
            <p class="text-center">Enter your registered email address to receive a reset link.</p>
            <div class="form-group">
                <input type="email" class="form-control" name="email" id="id_email" placeholder="Email Address" required="required">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Send Link</button>
            </div>
            <p class="text-center"><a href="{% url 'Login' %}" name = 'Login'>Cancel</a></p>
        </form>
    </div>

    {% block footer %}
        <footer class="page-footer">
            <!-- Copyright -->
            <div class="footer-copyright text-center py-3 text-dark">
                © Copyright 2022 Neighbourhood
            </div>
            <!-- Copyright -->
        </footer>
    {% endblock %}
{% endblock %}

templates/ResetPasswordEmail.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
Admin
{% endautoescape %}